function Write_MuestreadosFile(PathFile, UserData)

% PathFile = 'Tester.txt';

%% Abrir Archivo
ID_File = fopen(PathFile,'w');

%% Numero de puntos de control
% Calcular numero de puntos de control
[n,~] = size(UserData.PC);
fprintf(ID_File,'[FACTORES DEL MODELO METEOROLÓGICO]\n');
fprintf(ID_File,'%d\n',n);
fprintf(ID_File,'\n');

%% Listado de varibles para puntos de control
fprintf(ID_File,'[LISTADO DE VARIABLES PARA PUNTOS DE CONTROL]\n');
fprintf(ID_File,['TA TAmin TAmax TAran HR RS PV U Ux Uy LCL LWC EV ETo SMI HU ',...
                'LAI psi theta ks n2v n2 C_usle ETP PH DTRjo LAIjo LAIopt S0 ',...
                'S1 S2 S3 S4 S5 E0 E1 E2 E3 E4 E5 I0 I1 I2 I3 I4 O4 U2 U3 U4 ',...
                'U5 AF3 Q2 Q5 Q5a Q5c Q5d Q5p H2 H5 H5b W5 W5b P5 A5 R5 D5 n5l ',...
                'n5b n5 arcS2S limS2S areS2S arcS2D limS2D areS2D arcS5S limS5S ',...
                'areS5S arcS5D limS5D areS5D arcE2S limE2S areE2S arcE2D limE2D ',...
                'areE2D arcE2E limE2E areE2E arcE5S limE5S areE5S arcE5D limE5D ',...
                'areE5D arcE5E limE5E areE5E E2Smax E2Dmax arcE5Smax limE5Smax ',...
                'areE5Smax arcI2D limI2D areI2D arcI5D limI5D areI5D ER5b PRx ',...
                'Lx Fx EntSed SalSed EST EDT E2ET E5ET EET ESDET Zwcrit Zmin ',...
                'Zmax Smin arcDV limDV areDV PFB','\n']);
FormatText = ['%d',repmat(' %d',1,length(UserData.Var_PC)-1),'\n'];
fprintf(ID_File,FormatText,UserData.Var_PC);
fprintf(ID_File,'\n');

%% Listado de puntos de control
fprintf(ID_File,'[LISTADO DE PUNTOS DE CONTROL]\n');
fprintf(ID_File,'X Y Nombre Estadístico\n');
Data = UserData.PC;
for i = 1:n   
    Tmp = [num2str(Data{i,1}),' ',num2str(Data{i,2}),' ',Data{i,3},' ',Data{i,4},'\n'];
    fprintf(ID_File,Tmp);
end
fprintf(ID_File,'\n');

%% Numero de tramos de control
% Calcular numero de puntos de control
[n,~] = size(UserData.TC);
fprintf(ID_File,'[NÚMERO DE TRAMOS DE CONTROL]\n');
fprintf(ID_File,'%d\n',n);
fprintf(ID_File,'\n');

%% Numero de tramos de control
fprintf(ID_File,'[LISTADO DE VARIABLES PARA TRAMOS DE CONTROL]\n');
fprintf(ID_File,['TA TAmin TAmax TAran HR RS PV U Ux Uy LCL LWC EV ETo SMI HU ',...
                'LAI psi theta ks n2v n2 C_usle ETP PH DTRjo LAIjo LAIopt S0 ',...
                'S1 S2 S3 S4 S5 E0 E1 E2 E3 E4 E5 I0 I1 I2 I3 I4 O4 U2 U3 U4 ',...
                'U5 AF3 Q2 Q5 Q5a Q5c Q5d Q5p H2 H5 H5b W5 W5b P5 A5 R5 D5 n5l ',...
                'n5b n5 arcS2S limS2S areS2S arcS2D limS2D areS2D arcS5S limS5S ',...
                'areS5S arcS5D limS5D areS5D arcE2S limE2S areE2S arcE2D limE2D ',...
                'areE2D arcE2E limE2E areE2E arcE5S limE5S areE5S arcE5D limE5D ',...
                'areE5D arcE5E limE5E areE5E E2Smax E2Dmax arcE5Smax limE5Smax ',...
                'areE5Smax arcI2D limI2D areI2D arcI5D limI5D areI5D ER5b PRx ',...
                'Lx Fx EntSed SalSed EST EDT E2ET E5ET EET ESDET Zwcrit Zmin ',...
                'Zmax Smin arcDV limDV areDV PFB','\n']);
FormatText = ['%d',repmat(' %d',1,length(UserData.Var_TC)-1),'\n'];
fprintf(ID_File,FormatText,UserData.Var_TC);
fprintf(ID_File,'\n');

%% Listado de tramos de control
fprintf(ID_File,'[LISTADO DE TRAMOS DE CONTROL]\n');
fprintf(ID_File,'X1 Y1 X2 Y2 Nombre\n');
Data = UserData.TC;
for i = 1:n   
    Tmp = [num2str(Data{i,1}),' ',num2str(Data{i,2}),' ',num2str(Data{i,3}),...
            ' ',num2str(Data{i,4}),' ',Data{i,5},'\n'];
    fprintf(ID_File,Tmp);
end
fprintf(ID_File,'\n');

%% Listado de varibles para mapas
fprintf(ID_File,'[LISTADO DE VARIABLES PARA MAPAS]\n');
fprintf(ID_File,['TA TAmin TAmax TAran HR RS PV U Ux Uy LCL LWC EV ETo SMI HU ',...
                'LAI psi theta ks n2v n2 C_usle ETP PH DTRjo LAIjo LAIopt S0 ',...
                'S1 S2 S3 S4 S5 E0 E1 E2 E3 E4 E5 I0 I1 I2 I3 I4 O4 U2 U3 U4 ',...
                'U5 AF3 Q2 Q5 Q5a Q5c Q5d Q5p H2 H5 H5b W5 W5b P5 A5 R5 D5 n5l ',...
                'n5b n5 arcS2S limS2S areS2S arcS2D limS2D areS2D arcS5S limS5S ',...
                'areS5S arcS5D limS5D areS5D arcE2S limE2S areE2S arcE2D limE2D ',...
                'areE2D arcE2E limE2E areE2E arcE5S limE5S areE5S arcE5D limE5D ',...
                'areE5D arcE5E limE5E areE5E E2Smax E2Dmax arcE5Smax limE5Smax ',...
                'areE5Smax arcI2D limI2D areI2D arcI5D limI5D areI5D ER5b PRx ',...
                'Lx Fx EntSed SalSed EST EDT E2ET E5ET EET ESDET Zwcrit Zmin ',...
                'Zmax Smin arcDV limDV areDV PFB','\n']);
FormatText = ['%d',repmat(' %d',1,length(UserData.Var_Map)-1)];
fprintf(ID_File,FormatText,UserData.Var_Map);

%% Cerrar Archivo
fclose(ID_File);